name: Bug Report
description: Submit a bug report.
title: "[Bug]: "
labels: Bug
body:
  - type: checkboxes
    attributes:
      label: Search for Similar Reports
      description: |
        Please use the search feature on the repository's [Issues](https://github.com/jordanbaird/Ice/issues) page to see if a report already exists for the bug you encountered. Make sure to include both open and closed issues in your search.

        **Important**: Only submit a new issue if the bug you encountered hasn't been reported in an existing open issue, or if a regression has occurred with a previously closed issue.
      options:
        - label: I have searched existing issues for similar reports
          required: true
  - type: textarea
    attributes:
      label: Description
      placeholder: A clear and concise description of the bug...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reliably reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: App Version
      placeholder: e.g. 1.2.3
    validations:
      required: true
  - type: input
    id: macos_version
    attributes:
      label: macOS Version
      placeholder: e.g. 15.3.2
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      placeholder: Screenshots, screen recordings, logs, crash reports, or anything else you think might be helpful...
