name: Bug Report
description: File a bug report
title: "[Bug]: <bug title>"
labels: bug
body:
  - type: checkboxes
    attributes:
      label: Check existing and frequent issues
      description: Check existing issues to prevent duplicates. Only submit a new issue if you feel it has not been covered by an existing issue, or if a regression has occurred.
      options:
        - label: I have checked existing issues and believe that my issue is not a duplicate
          required: true
        - label: I have read the [Frequent Issues](Documentation/FREQUENT_ISSUES.md) document, and my issue is not included there
          required: true
  - type: textarea
    attributes:
      label: Description
      placeholder: A clear and concise description of the bug...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reliably reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    attributes:
      label: Ice Version
      placeholder: e.g. 1.2.3
    validations:
      required: true
  - type: input
    attributes:
      label: macOS Version
      placeholder: e.g. 14.4.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Relevant screenshots or screen recordings.
      placeholder: (optional)
