name: Feature Request
description: Request a feature or suggest an idea.
title: "[Feature Request]: "
labels: Feature
body:
  - type: checkboxes
    attributes:
      label: Search for Similar Requests
      description: |
        Please use the search feature on the repository's [Issues](https://github.com/jordanbaird/Ice/issues) page to see if this feature has already been requested. Make sure to include both open and closed issues in your search.

        **Important**: Only submit a new issue if the feature you want hasn't been requested in another issue.
      options:
        - label: I have searched existing issues for similar requests
          required: true
  - type: textarea
    attributes:
      label: Description
      placeholder: A clear and concise description of the feature...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      placeholder: Screenshots, screen recordings, mockups, or anything else you think might be helpful...
